# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MainApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MainApp
  pod 'DummyFramework', :path => '../'

  target 'MainAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MainAppUITests' do
    # Pods for testing
  end

end
